default_language_version:
    python: python3.10
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.275
    hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix, --exclude, alembic]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--safe,  --exclude, alembic]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-yaml
        args:
        -   --unsafe
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
